<?php

namespace app\controllers;

use app\models\ImageCollection;
use app\models\ImageForm;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\UploadedFile;

class ImagesController extends \yii\web\Controller
{
    public function afterAction($action, $result)
    {
        if ($action->actionMethod == 'actionAddImage' and \Yii::$app->request->post()) {
            $user_message = \Yii::$app->cache->get('user_message');
            if (!empty($user_message['user_email'])) {
                $message = !empty($user_message['user_message']) ? '' : 'Произошла некая ошибка загрузки изображения';
                \Yii::$app->mailer->compose()
                    ->setFrom('org@email.com')
                    ->setTo($user_message['user_email'])
                    ->setSubject('Загрузка изображения на сайте ' . Url::base())
                    ->setTextBody('Результат загрузки изображения: ' . $message)
                    ->send();

                \Yii::$app->cache->delete('user_message');
            }
        }

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $query = ImageCollection::find()->where('deleted = 0');
        $pagination = new Pagination([
            'defaultPageSize' => 9,
            'totalCount' => $query->count()
        ]);

        $images = $query->orderBy('added')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'images' => $images,
            'pagination' => $pagination
        ]);
    }

    public function actionAddImage()
    {
        $model = new ImageCollection();
        if (\Yii::$app->request->post()) {
            $request = \Yii::$app->request->post();
            $model->load($request);
            $model->img_file = UploadedFile::getInstance($model, 'img_file');
            if ($model->upload()) {
                //отключаем вторую валидацию, т.к. выше мы все проверили.
                if ($model->save(false)) {
                    $result['user_email'] = $model->email;
                    $result['user_message'] = 'Сообщение успешно загружено';
                } else {
                    $result = ['user_email' => $model->email, 'user_message' => 'Не удалось сохранить ваше изображение.'];
                }
            } elseif ($model->hasErrors()) {
                if (!key_exists('email', $model->errors)) {
                    $error_message = '';
                    foreach ($model->errors as $error) {
                        $error_message .= $error . '<br>';
                    }
                    $result = ['user_email' => $model->email, 'user_message' => $error_message];
                } else $result = false;
            }


            if (!empty($result)) {
                \Yii::$app->cache->set('user_message', $result, 60);
                \Yii::$app->session->setFlash('info', 'Изображения обработано. Проверьте вашу почту, чтобы узнать результаты загрузки изображения.');
            } else {
                \Yii::$app->session->setFlash('info', 'Произошла внутренняя ошибка при попытке сохранить ваше изображение. Попробуйте позже или свяжитесь с тех. поддержкой');
            }

            $this->redirect('index');
        }

        return $this->render('addImage', ['model' => $model]);
    }
}
